config/routes.rb
Rails.application.routes.draw do

 
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    confirmations: "confirmations"
  }
  resources :users, only: :index
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :galleries do
    resources :likes
  end
  root 'static_pages#home' 
  get '/home', to: 'static_pages#home' 
  get '/gallery', to: 'galleries#gallery'
  get '/users/show',to: 'users#show'
  resources :users, only: [:show]
  # get '/search', to: 'gallery_search#new_search', as:'new_search'
  post '/search_galleries', to: 'gallery_search#search_galleries', as:'search_galleries'
  get '/search_box', to: 'search#search_box', as:'search_box'
  post '/showgalleries', to: 'search#showgalleries', as:'showgalleries'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    include PgSearch::Model
    belongs_to :user
    has_many :likes, dependent: :destroy
    mount_uploader :image, ImageUploader
    validate :image_size_validation
    validates :image, presence: true
    validates :title, presence: true

    pg_search_scope :search, :against =>[:title, :image]
    # multisearchable against: [:title, :image]
    # searchable do
    #     text :title,:image, :user_id
    # end
    
    

    private
        def image_size_validation
            errors[:image] << "should be less than 2MB" if image.size > 2.0.megabytes
        end

        
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gallery
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  include PgSearch::Model
  multisearchable against: :name
  has_many :galleries,dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: "Follower", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Follower", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :followers
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         def self.to_csv
          attributes = %w{id name email}
      
          CSV.generate(headers: true) do |csv|
            csv << attributes
      
            all.find_each do |user|
              csv << attributes.map{ |attr| user.send(attr) }
            end
          end
        end
  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :configure_permitted_parameters, if: :devise_controller?
     include Pundit
     rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
          end

        
  
          def authenticate_admin_user!
               unless current_user.admin == true 
                    redirect_to galleries_path
               end
          end

          def user_not_authorized
               flash[:danger]="Access Deny"
               redirect_to galleries_path
          end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
    private

    def after_confirmation_path_for(resource_name, resource)
        sign_in(resource)
        galleries_path

    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
    before_action :authenticate_user!
    def index
        if params[:query].present?
            @gallery = Gallery.search(params[:query]).includes(:user)
        else
            @gallery = Gallery.includes(:user)
        end
       
    end

    def show
        @gallery = Gallery.find(params[:id])
        @user=@gallery.user
    end

    def new
        @gallery = Gallery.new
    end

    def create
        @gallery = current_user.galleries.build(gallery_params)

        if @gallery.save
            redirect_to @gallery
        else
            render :new
        end
    end

    def edit
        @gallery = Gallery.find(params[:id])
    end
    
    def update
        
        
        @gallery = Gallery.find(params[:id])
        authorize @gallery
        if @gallery.update(gallery_params)
            redirect_to @gallery
        else
            render :edit
        end

    end

    def destroy
        @gallery = Gallery.find(params[:id])
        authorize @gallery
        @gallery.destroy
        redirect_to root_path
    end

  
    private

    def gallery_params
        params.require(:gallery).permit(:title,:image)
    end
end

app/controllers/gallery_search_controller.rb
class GallerySearchController < ApplicationController
    skip_before_action :verify_authenticity_token
    def new_search
      
    end


    def search_galleries
    
        # @search =  Gallery.solr_search do 
        #     fulltext search_params[:title] 
        # end
        
        # @gallery = @search.results
    end


    private
    def search_params
        params.permit(:title, :image,:user_id,:name)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_gallery
    before_action :find_like, only: [:destroy]
  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @gallery.likes.create(user_id: current_user.id)
    end
    redirect_to gallery_path(@gallery)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to gallery_path(@gallery)
  end

  private
  def find_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end

  def find_like
    @like = @gallery.likes.find(params[:id])
   end
 

  def already_liked?
    Like.where(user_id: current_user.id, gallery_id:
    params[:gallery_id]).exists?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
        @gallery=Gallery.all
        @user=User.all
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def index
        @user=User.all
        respond_to do |format|
            format.html
            format.csv { send_data @user.to_csv, filename: "users-#{Date.today}.csv" }
        end
    end

    def show
        @user= User.find(params[:id])
        @users=User.all
        @gallery = Gallery.all

        # @gallery=@user.galleries
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gallery_search_helper.rb
module GallerySearchHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galleries/_form.html.erb
<div class="container">

    <% if @gallery.errors.any? %>
        <div id="error_explanation">
            <div class="alert alert-danger">
                The form contains <%= pluralize(@gallery.errors.count, "error") %>.
            </div>

            <ul>
                <% @gallery.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>


    <%= form_with model:@gallery do |form| %>

        <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= form.label :image %>
            <%= form.file_field  :image , class: "form-control"%>
        </div>

            <%= form.submit class: "btn btn-success"%>
        </div>
    <%end%>

</div>

app/views/galleries/edit.html.erb
<%= render 'form' %>

app/views/galleries/index.html.erb
<div class="indexbody container">
    <div class="row">
        <h1 class="col-md-12" style="margin-left: 12px" >Gallery</h1>
    </div>

        <a href="/users/<%= current_user.id %>" class="indexbtn">My Gallery --></a>

<div class="row">
    <% @gallery.each do |gallery| %>
        <div class="imagebox col-md-12 col-lg-12">
            <p class="card-title"><%= gallery.title %>:</p>

        
            <a class="imageindex card-img" href="/galleries/<%= gallery.id %>">
                <%= image_tag gallery.image.url(:thumb) if gallery.image_url %>
            </a>    
            <p class="footer">By <%= gallery.user.name %></p>
        <p class="footer"><%= gallery.likes.count %> <%= (gallery.likes.count) == 1 ? 'Like' : 'Likes'%></p>
        </div>
    <% end %>
</div>
<br/>
</div>

app/views/galleries/new.html.erb
<%= render 'form' %>

app/views/galleries/show.html.erb
<div class="container-fluid text-center">
    <div class="row">
        <div class="col-md-12">
        
            <h1><%=@gallery.title%></h1>
            <p>by <%=@gallery.user.name%></p>
            <%= image_tag @gallery.image.url(:cover), class: "imageshow" %>
            
            <% pre_like = @gallery.likes.find { |like| like.user_id == current_user.id} %>
            <% if pre_like %>
                <%= button_to 'Unlike', gallery_like_path(@gallery, pre_like), method: :delete, class: "btn btn-lg btn-danger" %>
            <% else %>
                <%= button_to 'Like', gallery_likes_path(@gallery), method: :post, class: "btn btn-lg btn-primary" %>
            <% end %>
            <br/>

            <p><%= @gallery.likes.count %> <%= (@gallery.likes.count) == 1 ? 'Like' : 'Likes'%></p>

            
            
        </div>
    </div>
<br/>

<div class="row">
    <div class="col-md-12 showlinks">

        <% if @gallery.user == current_user %> 
            <%= link_to "EDIT", edit_gallery_path(@gallery) %> | 
            <%= link_to "DELETE",gallery_path(@gallery), 
                        method: :delete,
                        data:{confirm:"ARE YOU SURE?"}%> |
            <%= link_to "HOME", galleries_path %> |
            <%= link_to "NEW", new_gallery_path %>
        <% end %>
        
    </div>

</div>

app/views/gallery_search/_new_search.html.erb
<form class="form-inline searchbox" method="post" action="/search_galleries">

    <div>
        
        <input type="text" class="form-control" name="title" value="<%=params[:title]%>" placeholder="search">
        <button class="btn btn-primary">Search</button>
    </div>

</form>

app/views/gallery_search/search_galleries.html.erb
<div class="container-fluid text-center">
    <div class="row">
        <div class="col-md-12">

          <% @gallery.each do |gallery| %>

              
                     <h1><%=gallery.title%></h1>
                     <p>by <%=gallery.user.name%></p>
                    <%= image_tag gallery.image.url(:cover), class: "imageshow" %>
                </div>
            <%end%>


               
           
        </div>
    </div>
</div>
<div class="container">
<div class="row">
<div class="col-md-12 showlinks text-center">
    <%= link_to "HOME", galleries_path %> |
    <%= link_to "NEW", new_gallery_path %>
</div>
</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <a class="navbar-brand">Gallery</a>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
 
        <li><a href="/galleries">Home <span class="sr-only">(current)</span></a></li>
       
        <li><a href="/galleries/new">Add a Image <span class="sr-only">(current)</span></a></li>

      <% if user_signed_in? %>
        <li><a href="/users/<%= current_user.id %>">My Gallery</a></li>
      <% end %>

        <li><%= link_to "Users", users_path %></li>

    </ul>
    
     <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li id="welcomeuser"><%= "Hi, #{current_user.name}" %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
         
      <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>

      <% end %>
      
    </ul>
  <form action="/galleries" accept-charset="UTF-8" method="get" class="form-inline searchbox">

    <input type="text" name="query" id="query" placeholder="Enter gallery title to search" class="form-control">
    <input type="submit" name="commit" value="Search" data-disable-with="Search" class="btn btn-primary">

  </form>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GalleryManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   <% flash.each do |message_type, message| %>
    <p class=" flashmessage alert alert-<%= message_type %>"><%= message %></p>
  <% end %>
    <%= render "layouts/nav" %>
  </head>

  <body>
    <%= yield %>
  </body>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

app/views/static_pages/home.html.erb
<div class="container text-center jumbotron">

    <%if user_signed_in?%>

        <h1 style = "font-size: 60px;">Welcome <%= current_user.name %>!</h1>
        <%= link_to "GALLERIES", galleries_path, class: "btn btn-primary" %>
         <% if user_signed_in? %>
             <a class="btn btn-primary" style="margin-left: 10px" href="/users/<%= current_user.id %>">MY GALLERY</a>
        <% end %>

    <%else%>
    
        <h1 style="font-size: 50px;">Log in to view or add Images</h1>
        <%= link_to 'Sign In', new_user_session_path, class: "btn btn-primary btn-lg" %>
        <h1 style="font-size: 50px;">New user? Sign up</h1>
        <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-primary btn-lg" %>

    <%end%>

</div>

app/views/users/index.html.erb
<div class="container">
    <%@user.each do |users|%>

        <h1><%= users.name %></h1>
        <li><%= users.email %></h1>
      
    <%end%>
    <br/>
    <br/>
    <a href="/users.csv"><button class="btn btn-success">export all</button></a>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 style="margin-left: 20px"><%= @user.name %>'s Gallery</h1>
        </div>
    </div>

    <div class="row">
            <%@user.galleries.each do |gallery| %>

                <div class="imagebox col-md-12">
                    <h2  class="card-title"><%= gallery.title %></h2>
                    <%= image_tag gallery.image.url(:thumb) , class: "imagegallery"%>
                </div>
            <%end%>

    </div>
</div>